version: '3'
services:
  database:
    container_name: keycloak-db
    image: postgres:10.6-alpine
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: 6S7asH2kZM
      POSTGRES_DB: keycloak-sso

  keycloak:
    container_name: keycloak-server
    image: quay.io/keycloak/keycloak:11.0.3
    ports:
      - "8080:8080"
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      DB_VENDOR: postgres
      DB_ADDR: keycloak-db
      DB_USER: postgres
      DB_PASSWORD: 6S7asH2kZM
      DB_DATABASE: keycloak-sso
    depends_on:
      - database
